package.name = "diogen"
package.description = "Dioxus lib"
package.license = "Apache-2.0"
package.repository = "https://github.com/unsudo-foundation/diogen"
package.keywords = [
    "dioxus",
    "component",
    "lib"
]
package.version = "0.4.0"
package.edition = "2024"
package.publish = true
dependencies.modwire.version = ">=0.1.0,<1.0.0"
dependencies.dioxus.version = ">=0.6.3,<1.0.0"
dependencies.web-sys.version = ">=0.3.77,<1.0.0"
dependencies.web-sys.features = [
    "Window",
    "MouseEvent",
    "EventTarget",
    "Event",
    "Element",
    "Document",
    "DomRect",
    "console"
]
dependencies.js-sys.version = ">=0.3.77,<1.0.0"
dependencies.wasm-bindgen.version = ">=0.2.1,<1.0.0"
dependencies.wasm-bindgen-futures.version = ">=0.4.5,<1.0.0"
dependencies.serde.version = ">=1.0.219,<2.0.0"
dependencies.serde-wasm-bindgen.version = ">=0.6.5,<1.0.0"
dependencies.paste.version = ">=1.0.15,<2.0.0"
dependencies.strum.version = ">=0.27.2,<1.0.0"
dependencies.strum_macros.version = ">=0.27.2,<1.0.0"
features.default = [
    "binding",
    "win-binding"
]
features.binding = []
features.win-binding = []