package.name = "diogen"
package.description = "Dioxus lib"
package.keywords = [
    "dioxus"
]
package.version = "0.1.0"
package.edition = "2024"
package.publish = true
dependencies.modwire.version = ">=0.1.0,<1.0.0"
dependencies.dioxus.version = ">=0.6.3,<1.0.0"
dependencies.web-sys.version = ">=0.3.77,<1.0.0"
dependencies.web-sys.features = [
    "Window",
    "MouseEvent",
    "EventTarget",
    "Event",
    "Element",
    "Document",
    "console"
]
dependencies.js-sys.version = ">=0.3.77,<1.0.0"
dependencies.wasm-bindgen.version = ">=0.2.1,<1.0.0"
dependencies.wasm-bindgen-futures.version = ">=0.4.5,<1.0.0"
dependencies.serde.version = "*"
dependencies.serde-wasm-bindgen = "*"
dependencies.paste.version = "*"
features.default = [
    "binding",
    "win-binding"
]
features.binding = []
features.win-binding = []